
    <div class="social_networks">
        <ul class="icons">
            <li><a href="https://www.facebook.com/Mendoolofficiel" target="blank"><i class="fab fa-facebook"></i></a></li>
            <li><a href="https://instagram.com/mendool_officiel?igshid=YmMyMTA2M2Y=" target="blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.tiktok.com/@mendool_officiel?_t=8ZhkPeEcxbq&_r=1" target="blank"><i class="fab fa-tiktok"></i></a></li>
            <li><a href="https://mobile.twitter.com/mendool_off" target="blank"><i class="fab fa-twitter"></i></a></li>            
        </ul>
    </div>  
    <div class="cgv_copyright">
        <div>
            <span>Copyright © <?= date('Y') ?> Created by Joanna Attali</span>
        </div>
    </div>
    <script src="./public/script/script.js"></script>

