
<section class="container">
    <div class="artist" id="main_part">
        <h1>La vie d'artiste</h1>
        <div class="artist_bio">
            <div class="image_artist">
                <img class="comic_mendool" src="public/medias/mendool_vibes.jpg" alt="comique Mendool">
            </div>
            <div class="bio">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero quae dolorem recusandae sed.
                Praesentium tenetur, nesciunt provident cum hic quis error laborum consequatur esse temporibus nostrum laboriosam eaque cumque laudantium.
                Velit reprehenderit enim deserunt consequuntur quam, ad unde architecto suscipit dolores 
                facilis porro. Eos sunt quas voluptatibus consequuntur culpa modi enim?</p>
                <p>Ullam accusantium quasi magni repellendus quam, optio quas quia?
                Repudiandae fugiat ad dignissimos neque deleniti minus aspernatur nesciunt ipsum accusamus 
                qui placeat inventore, voluptatibus blanditiis ea repellendus perspiciatis mollitia quis quo vero impedit. Nulla laboriosam consequatur dicta iure beatae?
                Assumenda quae odio modi, ipsum voluptatibus fugit nobis.</p>
                <p>Nostrum, minus doloremque dolorum mollitia ex, voluptas dignissimos perspiciatis harum reprehenderit a 
                libero eos minima, aut necessitatibus corrupti accusantium vitae ad sed.                    Ducimus, ullam totam nostrum eveniet officia expedita quam atque pariatur autem sapiente provident incidunt 
                similique placeat natus optio? Vero mollitia rem nulla quam cumque uga eligendi delectus doloribus ratione. 
                </p>
            </div>
        </div>
    </div>
</section>