
<!DOCTYPE html>
<html lang="fr">
	<!---------------chargement includes de mes partials + creation de mon visuel page mes Sketches---->
<head>
	<?php require "includes/partials/head.phtml"; ?>
</head>
<body>
	<header>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</header>

	<!-----------------------ICI J affiche ma page chronique avec ma liste de chroniques------------------------------->
	<div class="container">
		<main id="liste_chroniques">
			<h2>Mes chroniques</h2>
			<!--si la variable $session admin vaut vraie alors j affiche le bouton sinon je l affiche pas-->
			<?php
				$admin = $_SESSION['admin']?? false;
				if($admin == true){
					print('<div class="button_ajout">');
						print ('<a href="index.php?page=chronique&action=add" title="ajout chronique">Ajouter une chronique</a>');
					print('</div>');
				}
			?>
			<!------------liste de toutes mes chroniques que je recupere en faisant un foreach---------->
			<div class="container_card">
			<?php
				foreach ( $lesChroniques as $uneChronique){
					print ('<div class="card">');
							print('<h3><a href="index.php?page=chronique&action=view&id='.$uneChronique->getId().'" title="chronique">'.$uneChronique->getTitre().'</a></h3>');
							print('<div class="video">');
								print('<iframe src="'.$uneChronique->getLienVideo().'" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
							print('</div>');
							
							if($admin == true){
								print('<div class="button_modif_sup">');
									print('<a href="index.php?page=chronique&action=edit&id='.$uneChronique->getId().'" title="modifier">Modifier</a>');
								print('</div>');
								print('<div class="button_modif_sup">');
									print('<a href="index.php?page=chronique&action=delete&id='.$uneChronique->getId().'" title="supprimer">Supprimer</a>');
								print('</div>');
							}
					print('</div>');
				}	
			?>
			</div>
		</main>
	</div>

	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
</body>
</html>