
<!DOCTYPE html>
<html lang="fr">
	<!---------------chargement includes de mes partials + creation des boutons pour ajout/supr/modif des skecthes et tournees--->
<head>
	<?php require "includes/partials/head.phtml"; ?>
</head>
<body>
	<header>
		<?php require_once "includes/partials/navbar.phtml"; ?>
	</header>
	
	<main>
		<form class="connexion_form" id="login" action="" method="post">
			<section class="connexion">
				<div>
					<label for="ChLogin"></label>
					<input type="text" name="ChLogin" placeholder="Login">
				</div>
				<div>
					<label for="ChMdp"></label>
					<input type="password" name="ChMdp" placeholder="Mot de passe">
				</div>
				<div class="connexion_login">
					<button id="connexion_button" class="connexion-btn" type="submit">Connectez-vous</button>
					<a class="lien_inscription" href="index.php?page=user&action=inscription#inscription_form" title="inscrivez-vous">Inscrivez-vous</a>
				</div>
			</section>
        </form>
        <?php 
			print $message??'';//si $messag est renseigné sinn j 'ecris rien
		?>
	</main>
		
	<footer>
		<?php require_once "includes/partials/footer.phtml"; ?>
	</footer>
	
</body>
</html>